# Generated by Django 2.0.1 on 2018-02-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='author',
        ),
    ]
