# Generated by Django 2.0.1 on 2018-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20180210_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='date',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
