# Generated by Django 2.0.1 on 2018-02-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180215_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='occurrence',
        ),
    ]
