# Generated by Django 2.0.1 on 2018-08-27 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0006_menuitem_all_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='author',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
