# Generated by Django 2.0.1 on 2018-11-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20180827_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['start_date', 'id']},
        ),
    ]
