# Generated by Django 2.1.7 on 2019-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20181120_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='all_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='complete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
