# Generated by Django 2.1.7 on 2019-03-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20190301_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='end_date',
            new_name='complete_date',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='all_day',
        ),
    ]
