# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='step')),
                ('title', models.TextField(verbose_name='title')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipe.Recipe', verbose_name='recipe')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='noterecipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='noterecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reportedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='reportedrecipe',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='storedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='storedrecipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='NoteRecipe',
        ),
        migrations.DeleteModel(
            name='ReportedRecipe',
        ),
        migrations.DeleteModel(
            name='StoredRecipe',
        ),
    ]
