# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20170723_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('measurement', models.TextField(blank=True, null=True, verbose_name='measurement')),
                ('child_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_recipe', to='recipe.Recipe', verbose_name='subrecipe')),
                ('parent_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_recipe', to='recipe.Recipe', verbose_name='parent_recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='subrecipes',
            field=models.ManyToManyField(through='recipe.SubRecipe', to='recipe.Recipe', verbose_name='subrecipes'),
        ),
    ]
