# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20171114_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
