# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20171114_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='info',
            field=models.TextField(blank=True, help_text='enter information about the recipe', verbose_name='info'),
        ),
    ]
