# Generated by Django 2.0.1 on 2018-06-07 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20180129_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='old_rating',
        ),
    ]
