# Generated by Django 2.0.1 on 2018-06-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20180607_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='old_rating',
        ),
    ]
