# Generated by Django 2.0.1 on 2019-03-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20190301_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrecipe',
            name='quantity',
        ),
    ]
