# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20170723_2046'),
        ('ingredient', '0002_auto_20170127_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_group', to='recipe.Recipe', verbose_name='recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_group', to='ingredient.IngredientGroup', verbose_name='IngredientGroup'),
        ),
    ]
