# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 02:01
from __future__ import unicode_literals

from django.db import migrations


def migrate_ing(apps, schema_editor):
    IngredientGroup = apps.get_model('ingredient', 'IngredientGroup')
    Ingredient = apps.get_model('ingredient', 'Ingredient')
    for ingredient in Ingredient.objects.all():
        ingredient_group, created = IngredientGroup.objects.get_or_create(
            recipe_id=ingredient.recipe.id,
            defaults={'title': ''},
        )
        ingredient.ingredient_group = ingredient_group
        ingredient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0003_auto_20170723_2050'),
    ]

    operations = [
        migrations.RunPython(migrate_ing),
    ]
