# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20170723_2046'),
        ('ingredient', '0004_auto_20170723_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredient.IngredientGroup', verbose_name='IngredientGroup'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='recipe.Recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientgroup',
            unique_together=set([('title', 'recipe')]),
        ),
    ]
