# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_auto_20170725_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='recipe.Recipe', verbose_name='recipe'),
        ),
    ]
