# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_auto_20170725_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
    ]
