# Generated by Django 2.0.1 on 2018-01-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_remove_ingredient_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredient.IngredientGroup'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='recipe.Recipe'),
        ),
    ]
