# Generated by Django 2.0.1 on 2018-03-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_auto_20180129_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='denominator',
            field=models.FloatField(default=1, verbose_name='denominator'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='numerator',
            field=models.FloatField(default=1, verbose_name='numerator'),
        ),
    ]
