# Generated by Django 2.0.1 on 2018-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0010_auto_20180330_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='numerator',
            field=models.FloatField(default=0, verbose_name='numerator'),
        ),
    ]
