# Generated by Django 2.0.1 on 2018-11-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0011_auto_20180415_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
