# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
    ]
