# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_groceryitem_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryaisle',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['item']},
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='aisle',
        ),
        migrations.DeleteModel(
            name='GroceryAisle',
        ),
    ]
