# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20170128_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='item',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='title',
            field=models.CharField(default='e', max_length=550, verbose_name='title'),
            preserve_default=False,
        ),
    ]
