# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20170203_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='groceryshared',
            options={},
        ),
    ]
