# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20170728_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.GroceryList', verbose_name='grocery_list'),
        ),
    ]
