# Generated by Django 2.0.1 on 2018-11-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20180129_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryrecipe',
            name='list',
        ),
        migrations.RemoveField(
            model_name='groceryrecipe',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='GroceryRecipe',
        ),
    ]
