# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='News',
        ),
    ]
